title: POSEmuse Doodle App - Public Information
description: Official public information repository for the POSEmuse Doodle App.
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
